stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'Ubuntu-16.04'
    continueOnError: true
    steps:
    - checkout: self
    - checkout: Shared_Templates
    - script: |
        git status
